steps:
  # Build the container using modern Docker with BuildKit enabled
  - name: 'gcr.io/cloud-builders/docker'
    env:
      - 'DOCKER_BUILDKIT=1'
    args:
      - 'build'
      - '-t'
      - 'europe-west6-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/daesy-helper-bot-dev:latest'
      - '.'

# Automatically push the finished image to Artifact Registry
images:
  - 'europe-west6-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/daesy-helper-bot-dev:latest'

options:
  # This option ensures that the cache directories persist across builds
  requestedVerifyOption: 'VERIFIED'